name = "Zoo"
defaultTargets = [
    "zoo_set_theory",
    "zoo_arithmetic",
    "zoo_interpretability_logic",
    "zoo_propositional",
    "zoo_modal",
]

[[require]]
scope = "FormalizedFormalLogic"
name = "Foundation"
rev = "SnO2WMaN/issue725"

[[lean_lib]]
name = "Zoo"

[[lean_exe]]
name = "zoo_arithmetic"
root = "arithmetic"
supportInterpreter = true

[[lean_exe]]
name = "zoo_set_theory"
root = "set_theory"
supportInterpreter = true

[[lean_exe]]
name = "zoo_modal"
root = "modal"
supportInterpreter = true

[[lean_exe]]
name = "zoo_interpretability_logic"
root = "interpretability_logic"
supportInterpreter = true

[[lean_exe]]
name = "zoo_propositional"
root = "propositional"
supportInterpreter = true
