name = "Zoo"
defaultTargets = [
    "set_theory",
    "arith",
    "interpretability_logic",
    "propositional",
    "modal",
]

[[require]]
scope = "FormalizedFormalLogic"
name = "Foundation"
rev = "SnO2WMaN/issue725"

[[lean_lib]]
name = "Zoo"

[[lean_exe]]
name = "zoo_arith"
root = "Arith"
supportInterpreter = true

[[lean_exe]]
name = "zoo_setTheory"
root = "SetTheory"
supportInterpreter = true

[[lean_exe]]
name = "zoo_modal"
root = "Modal"
supportInterpreter = true

[[lean_exe]]
name = "zoo_interpretabilityLogic"
root = "InterpretabilityLogic"
supportInterpreter = true

[[lean_exe]]
name = "zoo_propositional"
root = "Propositional"
supportInterpreter = true
